version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.3
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - node/install:
          node-version: '16.14'
      # installing all dependencies for the frontend
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      # installing all dependencies for the backend
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      # building the frontend
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # building the backend
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      # deploying the backend
      - run:
          name: Back-End deploy
          command: |
            npm run backend:deploy
      # deploying the frontend
      - run:
          name: Front-End deploy
          command: |
            npm run frontend:deploy